### ISSUE TITLE
Uncaught TypeError: Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by srissel** [imdone/imdone-atom#8] opened 2015-08-07 07:04 UTC
Steps to reproduce:

1. Added TODO-Task in a file: "// TODO: foo bar"
2. Right-clicked on this file in Atom's tree and chose "show Tasks - iMIDone"
3. New file tab "Template Issues" opened, with content
"Loading template Issues.
It's gonna be legen... wait for it."

**Atom Version**: 1.0.5
**System**: BTXNB40
**Thrown From**: [imdone-atom](https://github.com/imdone/imdone-atom) package, v1.1.10

### Stack Trace

Uncaught TypeError: Cannot read property 'exclude' of undefined

```
At C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:379

TypeError: Cannot read property 'exclude' of undefined
  at Repository.shouldExclude (C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\lib\repository.js:379:21)
  at EventEmitter.repo.watcher.chokidar.watch.ignored [as _isIgnored] (C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-watched-fs-store.js:43:28)
  at EventEmitter.FSWatcher._handle (C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\chokidar\index.js:339:12)
  at EventEmitter.<anonymous> (C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\chokidar\index.js:417:17)
  at Array.forEach (native)
  at EventEmitter.FSWatcher.add (C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\chokidar\index.js:416:9)
  at Object.exports.watch (C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\node_modules\chokidar\index.js:455:33)
  at Repository.repo.initWatcher (C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-watched-fs-store.js:39:29)
  at C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-watched-fs-store.js:21:14
  at C:\Users\srissel\.atom\packages\imdone-atom\node_modules\imdone-core\lib\mixins\repo-fs-store.js:38:16
  at FSReqWrap.oncomplete (fs.js:77:15)

```

### Commands

```
     -3:36.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -3:31.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:29.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  4x -3:28.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:27.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -3:27.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:27.2.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -3:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:56.4.0 ctrl-last-tab:next (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  4x -1:36.8.0 expose:toggle (div.settings-view.pane-item)
     -0:35.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:24.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:19.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
compare-files, v0.6.2
ctrl-last-tab, v0.2.0
expose, v0.4.0
highlight-selected, v0.10.1
imdone-atom, v1.1.10
language-groovy, v0.4.0
pretty-json, v0.4.1
Sublime-Style-Column-Selection, v1.3.0

# Dev
No dev packages
```

**Comment by filipesilva** [comment] 2015-08-07 09:07
Same here.

**Comment by piascikj** [comment] 2015-08-08 15:01
Fixed by modifying uri with encodeURIComponent

**Closed by piascikj** 2015-08-08 15:01 UTC
Labels: bug

**Comment by filipesilva** [comment] 2015-08-08 15:36
Cheers!

**Comment by filipesilva** [comment] 2015-08-18 09:02
Now I'm also getting this error when modifying the `exclude` regex in `.imdone/config.json`. Everything still works though.

**Comment by piascikj** [comment] 2015-08-18 14:38
@filipesilva Can you open a new ticket for that one?  It would help if I had the stack trace.  As a work around for excluding files you could create an .imdoneignore file.

**Comment by filipesilva** [comment] 2015-08-18 15:01
I tried reproducing it right now, but I didn't get an error this time. I remember it was this exact error though, because it had a link to this issue. If I get it again, I'll try to gather more information.

The error just appeared once, and I restarted atom, and then the excludes worked.
